### ISSUE TITLE
chore: convert text to venue

### ISSUE THREAD

**Issue by razbakov** [we-dance/platform#158]
As a Developer I need a function `getVenueFromText(input): Venue` so that I can implement #143 and #101

It should return existing venue from venues collection (find by place_id) or add new one.

Examples of input:
- "Marienplatz"
- "Marienplatz, Munich"

```
console.log(getVenueFromText('Marienplatz')) 
```

should output this object:

Return:
```js
{
  name: suggestion.name,
  id: suggestion.place_id,
  rooms: '',
  map: '',
  address: suggestion.value,
  createdAt: Date.now(),
}
```

References: 
- https://github.com/we-dance/platform/blob/main/components/TInput/TInputAddress.vue
- https://github.com/we-dance/platform/blob/main/components/TInput/TInputVenue.vue
- https://developers.google.com/maps/documentation/javascript/places
- https://developers.google.com/maps/documentation/javascript/reference/places-service#PlaceResult

**Comment by amanuela97** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/WeDance-61e70d8b462b5400201aab2d/issues/we-dance/platform/158?planning-poker) with ZenHub @larrycoal @nelson2411 @razbakov @Stefanacef
