### ISSUE TITLE
chore: convert text to date

### ISSUE THREAD

**Issue by razbakov** [we-dance/platform#159]
As a Developer I need a function `getDateFromText(input): Date` so that I can implement #143 and #101

Examples of input:
- 22.01
- 22.01.2022
- 22 January 2022

Return:
- `new Date("2022-01-22")`

**Comment by amanuela97** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/WeDance-61e70d8b462b5400201aab2d/issues/we-dance/platform/159?planning-poker) with ZenHub @larrycoal @nelson2411 @razbakov @Stefanacef

**Comment by razbakov** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/WeDance-61e70d8b462b5400201aab2d/issues/we-dance/platform/159?planning-poker) with ZenHub @amanuela97
