### ISSUE TITLE
Rename Istanbul, Turkey to İstanbul, Türkiye

### ISSUE THREAD

**Issue by timlmit** [we-dance/platform#226]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/23659530/202458155-88053c46-25aa-4d29-978d-592b78632deb.png">

Remove other non relevant locations for Istanbul
Turkey officially changes name at UN to Türkiye

https://www.theguardian.com/world/2022/jun/03/turkey-changes-name-to-turkiye-as-other-name-is-for-the-birds

**Comment by razbakov** [comment]
Done
