### ISSUE TITLE
add different types of Turkish dances(zeybek, horon)

### ISSUE THREAD

**Issue by yusuforak** [we-dance/platform#227]
zeybek, horon 

https://dansakademi.com.tr/zeybek/zeybek-dansi
https://www.lafsozluk.com/2013/07/horon-nedir-ne-demektir-anlami.html

**Comment by timlmit** [comment]
Added to the [spreadsheet ](https://docs.google.com/spreadsheets/d/1oCLW_c_Jr021AT6_gGngtFB94P_5ftSCJGp-XqdvRaM/edit#gid=0)
