### ISSUE TITLE
[Bug]: I can chat with myself

### ISSUE THREAD

**Issue by timlmit** [we-dance/platform#230]
**Steps to reproduce the behavior:**
1. Go to 'My profile'
2. Click on 'Contact' - 'Chat'

<img width="849" alt="image" src="https://user-images.githubusercontent.com/23659530/203390493-e5c9172d-52a1-41ed-8a2b-136f76162e64.png">

<img width="848" alt="image" src="https://user-images.githubusercontent.com/23659530/203391813-d1b35b1d-7406-46fa-b581-80b82463dcc7.png">

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by razbakov** [comment]
Solved
