### ISSUE TITLE
[Bug]: Incorrect locations in onboarding page

### ISSUE THREAD

**Issue by timlmit** [we-dance/platform#237]
**Steps to reproduce the behavior:**
1. Go to 'https://wedance.vip/onboarding'
2. Click on 'cities'
3. Scroll down

<img width="594" alt="image" src="https://user-images.githubusercontent.com/23659530/203842340-e74cd8d6-e0ec-435f-8f4b-6ac2fa0b9d0f.png">

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by razbakov** [comment]
Solved
