### ISSUE TITLE
[Bug]: Infinite load with Google sign in on mobile version

### ISSUE THREAD

**Issue by timlmit** [we-dance/platform#238]
### What happened?

**Steps to reproduce the behavior:**
1. Go to 'mobile version'
2. Click on 'Sign in with Google'
3. See infinite load

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by razbakov** [comment]
I can't reproduce the problem

**Comment by timlmit** [comment]
https://user-images.githubusercontent.com/23659530/204017331-5c2c18ce-861f-4a78-a8d8-a03fb73628c8.MP4

**Comment by razbakov** [comment]
Which browser is it? Is it incognito mode? Is it possible that 3d party cookies are disabled?

**Comment by timlmit** [comment]
Default settings
Normal mode
iPhone, iOS 16.1.1
Safari, Chrome

**Comment by timlmit** [comment]
I will test on Android and other configurations tomorrow

**Comment by timlmit** [comment]
I can't reproduce it on Android, just on iOS now...

**Comment by timlmit** [comment]
Same

**Comment by razbakov** [comment]
Solved
