### ISSUE TITLE
Add additional Turkish dance styles to the website

### ISSUE THREAD

**Issue by timlmit** [we-dance/platform#248]
![image](https://user-images.githubusercontent.com/23659530/204334960-212d0904-f398-43ed-8090-9517c1d3028c.png)

- Bar
- Hora
- Kasik Oyunyu
- Kolbash
- Samah
- Shiksaray
- Van
- Adiyaman

https://docs.google.com/spreadsheets/d/1oCLW_c_Jr021AT6_gGngtFB94P_5ftSCJGp-XqdvRaM/edit#gid=0

**Comment by timlmit** [comment]
@razbakov Please add asap

**Comment by razbakov** [comment]
Done
