### ISSUE TITLE
[Bug]: Improve Turkish localization for Istanbul page

### ISSUE THREAD

**Issue by timlmit** [we-dance/platform#249]
### What happened?

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/23659530/204493610-a2fe3e30-0902-473e-aef2-3f9de0ab76cb.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by timlmit** [comment]
https://wedance.vip/Istanbul

**Comment by razbakov** [comment]
Done in 90b45b7
