### ISSUE TITLE
[Bug]: Copy leading to date change on event page

### ISSUE THREAD

**Issue by timlmit** [we-dance/platform#258]
### What happened?

https://wedance.vip/events/MuHPW2zHl7AkMb1t16PC

https://user-images.githubusercontent.com/23659530/204804858-7aa8a527-a832-41e1-a361-79006aec1395.mov

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by timlmit** [comment]
<img width="927" alt="image" src="https://user-images.githubusercontent.com/23659530/204805538-6b8fd0f9-3de8-42e0-b88c-6ae7fac94d25.png">
Now I have several duplicates

**Comment by timlmit** [comment]
@razbakov please fix it

**Comment by razbakov** [comment]
@timlmit "Copy" means Create a copy of the event - https://t.me/WeDancePlatform/124
