### ISSUE TITLE
[Bug]: Correct the Sentence

### ISSUE THREAD

**Issue by iiio2** [we-dance/platform#336]
### What happened?

**Steps to reproduce the behavior:**
1. Go to 'https://github.com/we-dance'
3. Scroll down to 'the very first line in README.md'

**Expected behavior:**
This is said, "We are a educational non-profit organisation". I think It would be "We are an educational non-profit organisation". Because in educational, 'e' is vowel. So, before educational, it would be an.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by razbakov** [comment]
@iiio2 i thought you wanted to do PR with a fix?

**Comment by iiio2** [comment]
created a pr and the issue is fixed.
