### ISSUE TITLE
Filter as pills

### ISSUE THREAD

**Issue by razbakov** [we-dance/platform#68]
As a User I want to see legend of icons that are used in the calendar

Calendar page - https://wedance.vip/events

Actual:
- the event list uses a dropdown to choose the filter of the event type (TDropdown)
- TInputButtons breaks layout and doesn't support horizontal scroll

Expected:
- filter options are shown as pills, i.e. buttons in one line with horizontal scroll (TPills)

**Comment by ali27001** [comment]
Can you show an example used for this?

**Comment by razbakov** [comment]
Actual - dropdown:
![Screenshot_20211230-154157.png](https://user-images.githubusercontent.com/298778/147761635-4028e625-edf9-43ff-af75-1d129565fd5d.png)

Expected - buttons horizontally:
![IMG_20211230_154654_678.jpg](https://user-images.githubusercontent.com/298778/147761938-3f5f3553-5b27-4645-9ffe-3305fa451c89.jpg)
