### ISSUE TITLE
i18n: Event Editor

### ISSUE THREAD

**Issue by razbakov** [we-dance/platform#75]
As a translator I want to be able to localise these pages:
- Event Editor - https://wedance.vip/events/-/edit

Follow i18n style guide in #70

**Comment by nelson2411** [comment]
I think someone else is working on this task.

**Comment by razbakov** [comment]
@nelson2411 you can take it, no one is working on this one. @larrycoal is working on #77

**Comment by nelson2411** [comment]
One question, 
What is the component that needs to be translated?

- TItemEdit
- TPopupEdit
